"""Skill taxonomy: multilingual names, keywords (English, Kannada, Hindi, romanised 'Kanglish/Hinglish'),
related skills (for semantic matching + career suggestions) and base local rates."""

CATEGORIES = [
    {"id": "gardening", "icon": "🌱", "en": "Gardening", "kn": "ತೋಟದ ಕೆಲಸ", "hi": "बागवानी"},
    {"id": "cleaning", "icon": "🧹", "en": "Cleaning", "kn": "ಸ್ವಚ್ಛತೆ", "hi": "सफ़ाई"},
    {"id": "repair", "icon": "🔧", "en": "Repair", "kn": "ರಿಪೇರಿ", "hi": "मरम्मत"},
    {"id": "farm", "icon": "🚜", "en": "Farm work", "kn": "ಹೊಲದ ಕೆಲಸ", "hi": "खेती का काम"},
    {"id": "moving", "icon": "🚚", "en": "Moving & Loading", "kn": "ಸರಕು ಸಾಗಣೆ", "hi": "सामान ढुलाई"},
    {"id": "house", "icon": "🏠", "en": "House work", "kn": "ಮನೆ ಕೆಲಸ", "hi": "घर का काम"},
    {"id": "construction", "icon": "👷", "en": "Construction", "kn": "ಕಟ್ಟಡ ಕೆಲಸ", "hi": "निर्माण"},
    {"id": "event", "icon": "🎉", "en": "Event work", "kn": "ಸಮಾರಂಭ ಕೆಲಸ", "hi": "कार्यक्रम"},
    {"id": "digital", "icon": "💻", "en": "Digital work", "kn": "ಡಿಜಿಟಲ್ ಕೆಲಸ", "hi": "डिजिटल काम"},
    {"id": "other", "icon": "✨", "en": "Other", "kn": "ಇತರೆ", "hi": "अन्य"},
]

# unit: day | hour | job | tree ; rate = typical local rate for that unit (Udupi region, INR)
SKILLS = [
    # ---------- gardening ----------
    {"id": "garden_cleaning", "cat": "gardening", "icon": "🌿", "en": "Garden cleaning", "kn": "ತೋಟ ಸ್ವಚ್ಛತೆ", "hi": "बगीचे की सफ़ाई",
     "kw": ["garden", "garden clean", "backyard", "yard", "leaves", "weeds", "overgrown", "bush", "grass", "thota", "tota", "ತೋಟ", "ಹುಲ್ಲು", "ಗಿಡ", "बगीचा", "बाग", "घास", "bagicha", "ghas", "hullu"],
     "related": ["weeding", "lawn_mowing", "tree_trimming", "landscaping"], "unit": "day", "rate": 700},
    {"id": "tree_trimming", "cat": "gardening", "icon": "🌳", "en": "Tree trimming", "kn": "ಮರ ಕತ್ತರಿಸುವುದು", "hi": "पेड़ की छंटाई",
     "kw": ["tree", "branch", "branches", "trim", "cut tree", "prune", "mara", "ಮರ", "ಕೊಂಬೆ", "पेड़", "डाली", "ped", "dali", "kombe"],
     "related": ["garden_cleaning", "coconut_climbing"], "unit": "day", "rate": 900},
    {"id": "coconut_climbing", "cat": "gardening", "icon": "🌴", "en": "Coconut tree climbing", "kn": "ತೆಂಗಿನ ಮರ ಹತ್ತುವುದು", "hi": "नारियल पेड़ चढ़ना",
     "kw": ["coconut", "climb", "climber", "tree climb", "thengu", "tengu", "tenginakayi", "kayi", "ತೆಂಗು", "ತೆಂಗಿನ", "ಕಾಯಿ", "ಹತ್ತ", "नारियल", "चढ़", "nariyal"],
     "related": ["coconut_harvesting", "arecanut_harvesting", "tree_trimming"], "unit": "tree", "rate": 60},
    {"id": "coconut_harvesting", "cat": "gardening", "icon": "🥥", "en": "Coconut harvesting", "kn": "ತೆಂಗಿನಕಾಯಿ ಕೀಳುವುದು", "hi": "नारियल तोड़ना",
     "kw": ["coconut", "coconuts", "pluck", "remove coconut", "harvest coconut", "tegi", "keelu", "ತೆಂಗಿನಕಾಯಿ", "ಕೀಳು", "ತೆಗಿ", "नारियल तोड़", "nariyal"],
     "related": ["coconut_climbing", "arecanut_harvesting"], "unit": "tree", "rate": 60},
    {"id": "lawn_mowing", "cat": "gardening", "icon": "🌾", "en": "Lawn mowing", "kn": "ಹುಲ್ಲು ಕತ್ತರಿಸುವುದು", "hi": "घास कटाई",
     "kw": ["lawn", "mow", "mowing", "grass cut", "ಹುಲ್ಲು ಕತ್ತರಿ", "घास काट"], "related": ["garden_cleaning", "weeding"], "unit": "hour", "rate": 150},
    {"id": "landscaping", "cat": "gardening", "icon": "🏡", "en": "Landscaping & planting", "kn": "ಗಿಡ ನೆಡುವುದು", "hi": "पौधे लगाना",
     "kw": ["plant", "planting", "landscape", "pots", "sapling", "nursery", "ಗಿಡ ನೆಡು", "ಸಸಿ", "पौधा", "पौधे", "gida"],
     "related": ["garden_cleaning", "irrigation_repair"], "unit": "day", "rate": 800},
    # ---------- farm ----------
    {"id": "harvesting", "cat": "farm", "icon": "🌾", "en": "Crop harvesting", "kn": "ಕೊಯ್ಲು", "hi": "फसल कटाई",
     "kw": ["harvest", "harvesting", "paddy", "crop", "cutting crop", "koylu", "bhatta", "ಕೊಯ್ಲು", "ಭತ್ತ", "ಬೆಳೆ", "फसल", "कटाई", "धान", "fasal", "katai"],
     "related": ["farm_labour", "arecanut_harvesting"], "unit": "day", "rate": 700},
    {"id": "farm_labour", "cat": "farm", "icon": "🧑‍🌾", "en": "Farm labour", "kn": "ಕೃಷಿ ಕೂಲಿ", "hi": "खेत मज़दूरी",
     "kw": ["farm", "field", "agri", "agriculture", "farming", "gadde", "hola", "krishi", "ಗದ್ದೆ", "ಹೊಲ", "ಕೃಷಿ", "ಕೂಲಿ", "खेत", "खेती", "मज़दूर", "khet", "kheti", "coolie", "kooli"],
     "related": ["harvesting", "weeding", "spraying"], "unit": "day", "rate": 650},
    {"id": "weeding", "cat": "farm", "icon": "🌿", "en": "Weeding", "kn": "ಕಳೆ ತೆಗೆಯುವುದು", "hi": "निराई",
     "kw": ["weed", "weeding", "kale", "ಕಳೆ", "निराई", "खरपतवार"], "related": ["farm_labour", "garden_cleaning"], "unit": "day", "rate": 600},
    {"id": "spraying", "cat": "farm", "icon": "💦", "en": "Pesticide spraying", "kn": "ಔಷಧಿ ಸಿಂಪಡಣೆ", "hi": "दवा छिड़काव",
     "kw": ["spray", "spraying", "pesticide", "medicine spray", "ಔಷಧಿ", "ಸಿಂಪಡ", "छिड़काव", "दवा", "spray maadi"],
     "related": ["farm_labour", "arecanut_harvesting"], "unit": "day", "rate": 800},
    {"id": "arecanut_harvesting", "cat": "farm", "icon": "🌰", "en": "Arecanut harvesting", "kn": "ಅಡಿಕೆ ಕೊಯ್ಲು", "hi": "सुपारी तोड़ना",
     "kw": ["arecanut", "areca", "adike", "betel nut", "ಅಡಿಕೆ", "सुपारी", "supari"], "related": ["coconut_climbing", "spraying"], "unit": "day", "rate": 1000},
    {"id": "irrigation_repair", "cat": "farm", "icon": "🚿", "en": "Irrigation / pump repair", "kn": "ನೀರಾವರಿ ರಿಪೇರಿ", "hi": "सिंचाई मरम्मत",
     "kw": ["irrigation", "pump", "motor", "drip", "sprinkler", "borewell", "ಪಂಪ್", "ಮೋಟಾರ್", "ನೀರಾವರಿ", "पंप", "मोटर", "सिंचाई"],
     "related": ["plumbing", "electrical"], "unit": "job", "rate": 500},
    # ---------- cleaning ----------
    {"id": "house_cleaning", "cat": "cleaning", "icon": "🧽", "en": "House cleaning", "kn": "ಮನೆ ಸ್ವಚ್ಛತೆ", "hi": "घर की सफ़ाई",
     "kw": ["clean", "cleaning", "house clean", "sweep", "mop", "dust", "swachha", "kasa", "ಸ್ವಚ್ಛ", "ಗುಡಿಸ", "ಕಸ", "सफ़ाई", "सफाई", "झाड़ू", "pocha", "safai", "jhadu"],
     "related": ["deep_cleaning", "bathroom_cleaning", "house_help"], "unit": "hour", "rate": 150},
    {"id": "deep_cleaning", "cat": "cleaning", "icon": "✨", "en": "Deep cleaning", "kn": "ಆಳವಾದ ಸ್ವಚ್ಛತೆ", "hi": "डीप क्लीनिंग",
     "kw": ["deep clean", "full house clean", "shifting clean", "festival clean", "ಪೂರ್ತಿ ಸ್ವಚ್ಛ"], "related": ["house_cleaning", "bathroom_cleaning"], "unit": "day", "rate": 1200},
    {"id": "bathroom_cleaning", "cat": "cleaning", "icon": "🚽", "en": "Bathroom cleaning", "kn": "ಬಚ್ಚಲು ಸ್ವಚ್ಛತೆ", "hi": "बाथरूम सफ़ाई",
     "kw": ["bathroom", "toilet", "washroom", "bachhalu", "ಬಚ್ಚಲು", "ಶೌಚಾಲಯ", "बाथरूम", "शौचालय"], "related": ["house_cleaning"], "unit": "job", "rate": 400},
    {"id": "water_tank_cleaning", "cat": "cleaning", "icon": "🛢️", "en": "Water tank / well cleaning", "kn": "ಟ್ಯಾಂಕ್ / ಬಾವಿ ಸ್ವಚ್ಛತೆ", "hi": "टंकी सफ़ाई",
     "kw": ["tank", "sump", "well", "bavi", "ಟ್ಯಾಂಕ್", "ಬಾವಿ", "ಸಂಪ್", "टंकी", "कुआँ"], "related": ["house_cleaning", "plumbing"], "unit": "job", "rate": 800},
    {"id": "office_cleaning", "cat": "cleaning", "icon": "🏢", "en": "Office / shop cleaning", "kn": "ಅಂಗಡಿ ಸ್ವಚ್ಛತೆ", "hi": "दुकान सफ़ाई",
     "kw": ["office", "shop", "hotel", "restaurant", "ಅಂಗಡಿ", "ಆಫೀಸ್", "दुकान", "ऑफिस", "angadi", "dukaan"], "related": ["house_cleaning", "deep_cleaning"], "unit": "day", "rate": 700},
    # ---------- house ----------
    {"id": "cooking", "cat": "house", "icon": "🍳", "en": "Cooking", "kn": "ಅಡುಗೆ", "hi": "खाना बनाना",
     "kw": ["cook", "cooking", "chef", "food", "aduge", "ಅಡುಗೆ", "खाना", "रसोई", "khana"], "related": ["catering", "house_help"], "unit": "day", "rate": 800},
    {"id": "house_help", "cat": "house", "icon": "🏠", "en": "House help", "kn": "ಮನೆ ಸಹಾಯಕ", "hi": "घरेलू मदद",
     "kw": ["maid", "house help", "helper at home", "domestic", "mane kelasa", "ಮನೆ ಕೆಲಸ", "ಕೆಲಸದವರು", "घर का काम", "बाई", "kaamwali"],
     "related": ["house_cleaning", "cooking", "laundry"], "unit": "day", "rate": 600},
    {"id": "elderly_care", "cat": "house", "icon": "🧓", "en": "Elderly / patient care", "kn": "ಹಿರಿಯರ ಆರೈಕೆ", "hi": "बुज़ुर्ग देखभाल",
     "kw": ["elder", "elderly", "patient", "caretaker", "nurse", "old age", "ಆರೈಕೆ", "ಹಿರಿಯ", "ರೋಗಿ", "देखभाल", "बुज़ुर्ग", "मरीज़"], "related": ["house_help", "baby_sitting"], "unit": "day", "rate": 900},
    {"id": "baby_sitting", "cat": "house", "icon": "🧸", "en": "Baby sitting", "kn": "ಮಗು ನೋಡಿಕೊಳ್ಳುವುದು", "hi": "बच्चे की देखभाल",
     "kw": ["baby", "child", "kids", "nanny", "babysit", "ಮಗು", "ಮಕ್ಕಳು", "बच्चा", "बच्चे"], "related": ["elderly_care", "house_help"], "unit": "hour", "rate": 150},
    {"id": "laundry", "cat": "house", "icon": "👕", "en": "Washing & ironing", "kn": "ಬಟ್ಟೆ ಒಗೆಯುವುದು", "hi": "कपड़े धोना",
     "kw": ["laundry", "wash clothes", "iron", "ironing", "batte", "ಬಟ್ಟೆ", "ಇಸ್ತ್ರಿ", "कपड़े", "इस्त्री", "kapde"], "related": ["house_help"], "unit": "hour", "rate": 120},
    # ---------- repair ----------
    {"id": "plumbing", "cat": "repair", "icon": "🚰", "en": "Plumbing", "kn": "ಪ್ಲಂಬಿಂಗ್", "hi": "प्लंबिंग",
     "kw": ["plumber", "plumbing", "pipe", "leak", "tap", "burst", "water leak", "nalli", "ಪೈಪ್", "ನಲ್ಲಿ", "ಸೋರಿಕೆ", "पाइप", "नल", "लीक", "nal"],
     "related": ["water_tank_cleaning", "irrigation_repair"], "unit": "job", "rate": 400},
    {"id": "electrical", "cat": "repair", "icon": "💡", "en": "Electrician", "kn": "ಎಲೆಕ್ಟ್ರಿಷಿಯನ್", "hi": "बिजली मिस्त्री",
     "kw": ["electric", "electrician", "wiring", "fan", "light", "switch", "power", "current", "fuse", "ಕರೆಂಟ್", "ಫ್ಯಾನ್", "ಲೈಟ್", "ವೈರಿಂಗ್", "बिजली", "पंखा", "बत्ती", "bijli", "pankha"],
     "related": ["appliance_repair", "ac_repair", "irrigation_repair"], "unit": "job", "rate": 400},
    {"id": "carpentry", "cat": "repair", "icon": "🪚", "en": "Carpentry", "kn": "ಬಡಗಿ ಕೆಲಸ", "hi": "बढ़ई का काम",
     "kw": ["carpenter", "carpentry", "wood", "door", "furniture repair", "cupboard", "badagi", "ಬಡಗಿ", "ಮರದ", "ಬಾಗಿಲು", "बढ़ई", "लकड़ी", "दरवाज़ा"],
     "related": ["furniture_moving", "painting"], "unit": "day", "rate": 1000},
    {"id": "ac_repair", "cat": "repair", "icon": "❄️", "en": "AC repair", "kn": "ಎಸಿ ರಿಪೇರಿ", "hi": "एसी मरम्मत",
     "kw": ["ac", "air conditioner", "cooling", "fridge", "refrigerator", "ಎಸಿ", "ಫ್ರಿಜ್", "एसी", "फ्रिज"], "related": ["electrical", "appliance_repair"], "unit": "job", "rate": 600},
    {"id": "appliance_repair", "cat": "repair", "icon": "🔌", "en": "Appliance repair", "kn": "ಉಪಕರಣ ರಿಪೇರಿ", "hi": "उपकरण मरम्मत",
     "kw": ["washing machine", "mixer", "tv", "appliance", "geyser", "ಮಿಕ್ಸಿ", "ಟಿವಿ", "मिक्सर", "टीवी", "गीज़र"], "related": ["electrical", "ac_repair"], "unit": "job", "rate": 450},
    {"id": "mobile_repair", "cat": "repair", "icon": "📱", "en": "Mobile / computer repair", "kn": "ಮೊಬೈಲ್ ರಿಪೇರಿ", "hi": "मोबाइल मरम्मत",
     "kw": ["mobile", "phone repair", "computer", "laptop", "screen", "ಮೊಬೈಲ್", "ಕಂಪ್ಯೂಟರ್", "मोबाइल", "कंप्यूटर", "लैपटॉप"], "related": ["computer_basics", "appliance_repair"], "unit": "job", "rate": 400},
    {"id": "welding", "cat": "repair", "icon": "🔥", "en": "Welding", "kn": "ವೆಲ್ಡಿಂಗ್", "hi": "वेल्डिंग",
     "kw": ["weld", "welding", "gate", "grill", "iron gate", "ವೆಲ್ಡಿಂಗ್", "ಗೇಟ್", "वेल्डिंग", "गेट", "ग्रिल"], "related": ["construction_helper", "vehicle_mechanic"], "unit": "job", "rate": 700},
    {"id": "vehicle_mechanic", "cat": "repair", "icon": "🛵", "en": "Vehicle mechanic", "kn": "ವಾಹನ ಮೆಕ್ಯಾನಿಕ್", "hi": "गाड़ी मिस्त्री",
     "kw": ["mechanic", "bike", "scooter", "car repair", "puncture", "vehicle", "gaadi", "ಬೈಕ್", "ಗಾಡಿ", "ಪಂಕ್ಚರ್", "गाड़ी", "बाइक", "पंचर"], "related": ["welding", "driving"], "unit": "job", "rate": 400},
    # ---------- moving ----------
    {"id": "loading_unloading", "cat": "moving", "icon": "📦", "en": "Loading / unloading", "kn": "ಲೋಡಿಂಗ್ / ಅನ್‌ಲೋಡಿಂಗ್", "hi": "लोडिंग / अनलोडिंग",
     "kw": ["load", "loading", "unload", "unloading", "lorry", "truck", "sacks", "bags", "godown", "warehouse", "ಲೋಡ್", "ಲಾರಿ", "ಚೀಲ", "लोड", "ट्रक", "बोरी", "hamali", "ಹಮಾಲಿ", "हमाली"],
     "related": ["furniture_moving", "delivery_helper", "packing"], "unit": "hour", "rate": 150},
    {"id": "furniture_moving", "cat": "moving", "icon": "🛋️", "en": "Furniture / house shifting", "kn": "ಮನೆ ಬದಲಾವಣೆ", "hi": "सामान शिफ्टिंग",
     "kw": ["move", "moving", "shift", "shifting", "furniture", "boxes", "carry", "lift", "ಶಿಫ್ಟ್", "ಸಾಮಾನು", "ಪೆಟ್ಟಿಗೆ", "शिफ्ट", "सामान", "डिब्बे", "saamaan"],
     "related": ["loading_unloading", "packing"], "unit": "hour", "rate": 170},
    {"id": "packing", "cat": "moving", "icon": "🎁", "en": "Packing", "kn": "ಪ್ಯಾಕಿಂಗ್", "hi": "पैकिंग",
     "kw": ["pack", "packing", "ಪ್ಯಾಕ್", "पैक"], "related": ["furniture_moving", "loading_unloading"], "unit": "hour", "rate": 130},
    {"id": "delivery_helper", "cat": "moving", "icon": "🛵", "en": "Delivery helper", "kn": "ಡೆಲಿವರಿ ಸಹಾಯಕ", "hi": "डिलीवरी हेल्पर",
     "kw": ["delivery", "deliver", "courier", "parcel", "ಡೆಲಿವರಿ", "ಪಾರ್ಸೆಲ್", "डिलीवरी", "पार्सल"], "related": ["driving", "loading_unloading"], "unit": "hour", "rate": 140},
    {"id": "driving", "cat": "moving", "icon": "🚗", "en": "Driver", "kn": "ಚಾಲಕ", "hi": "ड्राइवर",
     "kw": ["driver", "drive", "driving", "car driver", "chalaka", "ಡ್ರೈವರ್", "ಚಾಲಕ", "ड्राइवर", "गाड़ी चलाना"], "related": ["delivery_helper", "vehicle_mechanic"], "unit": "day", "rate": 900},
    # ---------- construction ----------
    {"id": "masonry", "cat": "construction", "icon": "🧱", "en": "Mason", "kn": "ಮೇಸ್ತ್ರಿ", "hi": "राजमिस्त्री",
     "kw": ["mason", "masonry", "brick", "wall", "plaster", "cement", "compound", "mestri", "ಗೋಡೆ", "ಇಟ್ಟಿಗೆ", "ಸಿಮೆಂಟ್", "ಮೇಸ್ತ್ರಿ", "दीवार", "ईंट", "सीमेंट", "मिस्त्री", "mistri"],
     "related": ["construction_helper", "tiling"], "unit": "day", "rate": 1100},
    {"id": "painting", "cat": "construction", "icon": "🎨", "en": "Painting", "kn": "ಬಣ್ಣ ಹಚ್ಚುವುದು", "hi": "पेंटिंग",
     "kw": ["paint", "painting", "painter", "colour", "color", "whitewash", "banna", "ಬಣ್ಣ", "ಪೇಂಟ್", "पेंट", "रंग", "पुताई", "rang"],
     "related": ["construction_helper", "carpentry"], "unit": "day", "rate": 900},
    {"id": "tiling", "cat": "construction", "icon": "⬛", "en": "Tiling", "kn": "ಟೈಲ್ಸ್ ಕೆಲಸ", "hi": "टाइल का काम",
     "kw": ["tile", "tiles", "tiling", "flooring", "granite", "ಟೈಲ್ಸ್", "ನೆಲ", "टाइल", "फर्श"], "related": ["masonry"], "unit": "day", "rate": 1100},
    {"id": "construction_helper", "cat": "construction", "icon": "⛏️", "en": "Construction helper", "kn": "ಕಟ್ಟಡ ಸಹಾಯಕ", "hi": "निर्माण मज़दूर",
     "kw": ["construction", "helper", "labour", "labor", "digging", "sand", "concrete", "site", "ಕಟ್ಟಡ", "ಮರಳು", "ಅಗೆ", "ಗುಂಡಿ", "निर्माण", "खुदाई", "रेत", "मज़दूरी", "majdoor"],
     "related": ["masonry", "loading_unloading"], "unit": "day", "rate": 700},
    {"id": "roofing", "cat": "construction", "icon": "🏚️", "en": "Roof repair", "kn": "ಮಾಡು ರಿಪೇರಿ", "hi": "छत मरम्मत",
     "kw": ["roof", "tiles roof", "sheet", "leak roof", "mangalore tiles", "ಮಾಡು", "ಹೆಂಚು", "ಛಾವಣಿ", "छत"], "related": ["masonry", "carpentry"], "unit": "day", "rate": 1000},
    # ---------- event ----------
    {"id": "event_helper", "cat": "event", "icon": "🎪", "en": "Event helper", "kn": "ಸಮಾರಂಭ ಸಹಾಯಕ", "hi": "इवेंट हेल्पर",
     "kw": ["event", "function", "wedding", "marriage", "party", "chairs", "pandal", "shamiyana", "serving", "ಮದುವೆ", "ಸಮಾರಂಭ", "ಕಾರ್ಯಕ್ರಮ", "ಚಪ್ಪರ", "शादी", "पार्टी", "समारोह", "shaadi", "maduve"],
     "related": ["catering", "decoration"], "unit": "day", "rate": 700},
    {"id": "catering", "cat": "event", "icon": "🍛", "en": "Catering / serving", "kn": "ಅಡುಗೆ ಬಡಿಸುವುದು", "hi": "खाना परोसना",
     "kw": ["catering", "serve food", "serving", "waiter", "ಬಡಿಸ", "परोस", "वेटर"], "related": ["cooking", "event_helper"], "unit": "day", "rate": 750},
    {"id": "decoration", "cat": "event", "icon": "🎈", "en": "Decoration", "kn": "ಅಲಂಕಾರ", "hi": "सजावट",
     "kw": ["decoration", "decorate", "flowers", "lights decoration", "ಅಲಂಕಾರ", "ಹೂವು", "सजावट", "फूल"], "related": ["event_helper"], "unit": "day", "rate": 800},
    # ---------- digital ----------
    {"id": "computer_basics", "cat": "digital", "icon": "🖥️", "en": "Computer / online forms help", "kn": "ಕಂಪ್ಯೂಟರ್ ಸಹಾಯ", "hi": "कंप्यूटर सहायता",
     "kw": ["online form", "form fill", "typing", "print", "aadhaar", "application", "ಫಾರ್ಮ್", "ಟೈಪಿಂಗ್", "फॉर्म", "टाइपिंग"], "related": ["data_entry", "mobile_repair"], "unit": "hour", "rate": 200},
    {"id": "data_entry", "cat": "digital", "icon": "⌨️", "en": "Data entry", "kn": "ಡೇಟಾ ಎಂಟ್ರಿ", "hi": "डेटा एंट्री",
     "kw": ["data entry", "excel", "billing", "accounts", "ಡೇಟಾ", "डेटा"], "related": ["computer_basics"], "unit": "hour", "rate": 200},
    {"id": "photography", "cat": "digital", "icon": "📷", "en": "Photography", "kn": "ಫೋಟೋಗ್ರಫಿ", "hi": "फोटोग्राफी",
     "kw": ["photo", "photographer", "video", "camera", "ಫೋಟೋ", "ವಿಡಿಯೋ", "फोटो", "वीडियो"], "related": ["event_helper", "decoration"], "unit": "day", "rate": 2000},
]

SKILL_MAP = {s["id"]: s for s in SKILLS}
CAT_MAP = {c["id"]: c for c in CATEGORIES}

# Checklists used by the AI job-description generator
TASK_TEMPLATES = {
    "garden_cleaning": ["Remove weeds and overgrown grass", "Collect fallen leaves", "Trim small bushes", "Collect and remove garden waste"],
    "tree_trimming": ["Cut overhanging branches safely", "Clear cut branches", "Stack wood / dispose waste"],
    "coconut_climbing": ["Climb coconut trees with safety gear", "Remove dry leaves and fronds"],
    "coconut_harvesting": ["Pluck ripe coconuts", "Lower coconuts safely", "Stack coconuts in one place"],
    "lawn_mowing": ["Mow lawn evenly", "Trim edges", "Collect grass clippings"],
    "landscaping": ["Dig pits for plants", "Plant saplings", "Add soil / manure", "Water the plants"],
    "harvesting": ["Cut ripe crop", "Bundle and stack", "Carry to storage / threshing area"],
    "farm_labour": ["General field work as instructed", "Carry tools and materials"],
    "weeding": ["Remove weeds by hand / tool", "Collect weeds away from crop"],
    "spraying": ["Mix spray as instructed", "Spray using safety mask and gloves", "Clean sprayer after work"],
    "arecanut_harvesting": ["Climb areca trees", "Harvest bunches", "Spray if required"],
    "irrigation_repair": ["Check pump / motor", "Fix pipe / drip leakages", "Test water flow"],
    "house_cleaning": ["Sweep and mop floors", "Dust furniture", "Clean kitchen surfaces"],
    "deep_cleaning": ["Clean every room top to bottom", "Clean windows and fans", "Kitchen and bathroom scrubbing"],
    "bathroom_cleaning": ["Scrub toilet and floor", "Clean tiles and taps", "Disinfect"],
    "water_tank_cleaning": ["Empty the tank", "Scrub walls and floor", "Disinfect and refill"],
    "office_cleaning": ["Sweep and mop", "Empty dustbins", "Clean desks and glass"],
    "cooking": ["Prepare meals as per menu", "Clean kitchen after cooking"],
    "house_help": ["Help with daily household chores", "Utensil washing", "Sweeping and mopping"],
    "elderly_care": ["Assist with daily activities", "Give medicines on time", "Keep company"],
    "baby_sitting": ["Take care of the child", "Feeding and play time"],
    "laundry": ["Wash clothes", "Dry and fold", "Iron clothes"],
    "plumbing": ["Find the leak / problem", "Repair or replace pipe / tap", "Test for leakage"],
    "electrical": ["Diagnose the electrical problem", "Repair wiring / switch / fan", "Test safely"],
    "carpentry": ["Repair / fit woodwork", "Fix doors, hinges or furniture"],
    "ac_repair": ["Diagnose AC / fridge", "Service and gas check", "Test cooling"],
    "appliance_repair": ["Diagnose appliance", "Repair / replace part", "Test working"],
    "mobile_repair": ["Diagnose device", "Repair screen / battery / software"],
    "welding": ["Measure and cut metal", "Weld gate / grill", "Paint welded joints"],
    "vehicle_mechanic": ["Diagnose vehicle problem", "Repair / puncture fix", "Test ride"],
    "loading_unloading": ["Load / unload goods carefully", "Stack goods neatly"],
    "furniture_moving": ["Carry furniture and boxes", "Load into vehicle", "Unload and place at new location"],
    "packing": ["Pack items safely", "Label boxes"],
    "delivery_helper": ["Pick up items", "Deliver to address", "Collect confirmation"],
    "driving": ["Drive vehicle safely", "Wait / return as needed"],
    "masonry": ["Brick / block work", "Plastering", "Curing"],
    "painting": ["Surface preparation", "Primer coat", "Two coats of paint", "Clean up"],
    "tiling": ["Level surface", "Lay tiles", "Grouting and cleaning"],
    "construction_helper": ["Carry materials", "Mix cement / concrete", "Site cleaning"],
    "roofing": ["Replace broken tiles / sheets", "Fix leakage", "Clean gutter"],
    "event_helper": ["Arrange chairs and tables", "Help guests", "Clean up after event"],
    "catering": ["Serve food to guests", "Refill dishes", "Clear tables"],
    "decoration": ["Set up decorations", "Flower / light arrangement", "Remove after event"],
    "computer_basics": ["Fill online forms", "Scan and upload documents", "Print copies"],
    "data_entry": ["Enter data accurately", "Verify entries"],
    "photography": ["Photograph the event", "Share edited photos"],
}

# Safety tips shown to workers per skill (safety-critical skills need extra care)
SAFETY_CRITICAL = {"coconut_climbing", "arecanut_harvesting", "tree_trimming", "electrical", "spraying", "roofing", "welding"}


def skill_name(sid: str, lang: str = "en") -> str:
    s = SKILL_MAP.get(sid)
    if not s:
        return sid
    return s.get(lang) or s["en"]
